#!/usr/local/bin/zsh
# This hook is sourced after every virtualenv is activated.

_OLD_RPS1="$RPS1"
RPS1="%{${fg_bold[white]}%}(%{${fg[green]}%}`basename \"$VIRTUAL_ENV\"`%{${fg_bold[white]}%})%{${reset_color}%}$RPS1"

proj_name=$(basename $VIRTUAL_ENV)
cd ~/projects/$proj_name
