# Sourced in interactive shells
# Should contain commands to set up aliases, functions, options, key bindings, etc.


source ~/.zsh/ohmyzsh.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/gcloud.zsh
source ~/.zsh/cuda.zsh
